- url.bs
- url.html
(I think the `<style>` change is Bikeshed now doing syntax highlighting in python with Pygments rather than in JS with Prism.)
> Link "ASCII hex digits" in IPv4 number parser to its definiton.

- url.bs
- url.html
~~(The whitespace-ignorant diff is easier to read)~~
This replaces the redundant "base URL must be in scope" requirement with a non-normative note ~~and an explicit *base-URL-is-null?* check in the *relative state* of the parsing algorithm.~~
This avoids an extraneous concept of scope ~~and further clarifies the behavior of the parser when the URL is relative but there is no base URL.~~
> Avoid implicitly defined "in scope" concept

- url.bs
- url.html
It was not obvious that application/x-www-form-urlencoded was a link
at all.
The markup had an extra </a>, suggesting this was originally intended.
> Link all of "application/x-www-form-urlencoded parsing" for clarity

- url.bs
- url.html
It was previously (per spec) a no-op.
This matches Firefox. (Chromium sets the port to zero.)
http://software.hixie.ch/utilities/js/live-dom-viewer/saved/4054
(`url.html` not regenerated since the latest version of Bikeshed does various things differently, generating unrelated diff churn.)
> `url.port = ""` sets the port number to null.

- url.bs
This regressed in 1eab2abb3806158fc7a550ac5b7deb2d6fff5602 in an
attempt to fix #50 for the second time… Not impressed.
Fixes #167.
> Parse IPv4 number "0x0a" correctly

- url.bs
Sometimes "single" is used to mean "any" which causes a different, incorrect interpretation of this algorithm (see https://github.com/jsdom/whatwg-url/pull/60). Clarify by using a more precise algorithm.
> Editorial: clarify the "shorten a path" algorithm

- url.bs
We’ll leave converting an OS filename to a JavaScript string to someone
else for now.
Fixes #109.
> Make application/x-www-form-urlencoded encode filenames

- url.bs
It turns out that preserving the ability to serialize an empty string
password is not something any implementation supports.
Fixes #181.
> No need for null passwords

- url.bs
This basically reverts bee5ad8041adfe6fc676c527bbc3f3cf4562ef67 as it
did not end up shipping in Firefox and the tentative conclusion is that
percent-decoding in URLs while parsing creates more trouble than it’s
worth.
We’ll still handle %2e when it’s part of a single-dot or double-dot
path segment.
Fixes #87.
> Stop decoding all %2e's in paths

- url.bs
This is necessary to define the behavior of the Location object’s
protocol attribute, which throws on syntax errors rather than silently
ignoring them as other protocol setters do.
Tests: https://github.com/w3c/web-platform-tests/pull/4412.
This is the cleanup work mentioned in
https://github.com/whatwg/html/commit/f0a73659b4046cc35a28855f3544dead66345689
that is happening way late.
> Return failure in state override scheme parsing

- url.bs
> Disallow invalid IPv4 in IPv6 parser

- url.bs
> Simplify constructing URLSearchParams

- url.bs
> Only support UTF-8 for the urlencoded parser

- url.bs
For URLs without a special scheme we cannot use the host parser
directly due to compatibility issues and we need to serialize slightly
differently too.
Fixes #148.
> Add opaque hosts

- url.bs
This is a theoretical issue once #185 lands, but as discussed it seems
good to address this anyway. Fixes #79.
> IPv4 parser: handle the empty string

- url.bs
> Host parser UTF-8 decoding should fail, not U+FFFD

- url.bs
This allows paths to be empty for non-special URLs and also takes that
into account when serializing.
Tests: https://github.com/w3c/web-platform-tests/pull/4586.
Fixes #212.
> Change path parsing for non-special URLs

- url.bs
> File state did not correctly deal with lack of base URL

- url.bs
Also point out that the variant with a trailing “|” is not conforming.
Fixes part of #209.
> Editorial: move Windows drive letter to a more logical location

- url.bs
This makes it a little easier to use with JSON.stringify().
Fixes #137.
> Define URL's toJSON()

- url.bs
Especially since browsers often violate this, which is rather bad for
security.
> Meta: state idempotence clearly as a goal

- url.bs
This:
* Stops the username/password/port APIs from functioning when host is
the empty string.
* Makes the host/hostname APIs work better with file URLs and adjusts
the file host state accordingly.
* Make setting host/hostname to the empty string impossible when they
have a username/password/port.
* Fixes #97.
> Cleanup API for file and non-special URLs

- url.bs
After 30362553e9ce9fc706d3492bd61886e399fc94e2 introduced the [URL-host parser](https://url.spec.whatwg.org/commit-snapshots/30362553e9ce9fc706d3492bd61886e399fc94e2/#concept-url-host-parser) rejects percent encoded code points in the non-special URLs host (because "%" is [forbidden host code point](https://url.spec.whatwg.org/#forbidden-host-code-point)).
The situation is paradoxical, because parser himself percent encodes some code points, actually producing invalid serialized URLs according to the current standard. 
URL's from #148 to test issue:
`unknown://%E2%80%A0/`
`notspecial://H%4fSt/path`
**Solution**
I suggest that forbidden host code points be checked on percent decoded code points. The decoded data will be used only for this purpose, so the <var>output</var> will not be …
> Fix: allow percent encoded code points in the non-special URLs host

- url.bs
Also stop saying "terminate these steps" and simply return.
Fixes #235.
> Editorial: use the Infra Standard for URL's path

- url.bs
Fixes #118 and fixes part of #209.
***
[Preview](https://url.spec.whatwg.org//branch-snapshots/annevk/concept-relations/) | [Diff](https://s3.amazonaws.com/pr-preview/whatwg/url/2f99502..annevk/concept-relations:8fc66a8.html)
> Explain how syntax relates to the parser for hosts and URLs

- url.bs
Also make sure the base URLs are actually represented in serialized
form by adding trailing slashes.
Fixes #209.
***
[Preview](https://url.spec.whatwg.org//branch-snapshots/annevk/validity-example/) | [Diff](https://s3.amazonaws.com/pr-preview/whatwg/url/50cb9ab..annevk/validity-example:4000ed7.html)
> Define which URLs are valid in the parser examples

- url.bs
Otherwise things get a little weird.
Fixes #231.
***
[Preview](https://url.spec.whatwg.org//branch-snapshots/annevk/copy-paths/) | [Diff](https://s3.amazonaws.com/pr-preview/whatwg/url/50cb9ab..annevk/copy-paths:fd8895f.html)
> Paths need to be copied from base URLs

- url.bs
I forgot about this in #218.
***
[Preview](https://url.spec.whatwg.org//branch-snapshots/annevk/valid-non-special-ipv6/) | [Diff](https://s3.amazonaws.com/pr-preview/whatwg/url/50cb9ab..annevk/valid-non-special-ipv6:b33172b.html)
> Make IPv6 addresses in special URLs valid

- url.bs
“Simple encode set” is effectively “C0 control encode set” so name it
that. And “default encode set” is only used for paths, so name it “path
encode set”.
Fixes #201.
***
[Preview](https://url.spec.whatwg.org//branch-snapshots/annevk/encode-set-names/) | [Diff](https://s3.amazonaws.com/pr-preview/whatwg/url/cdbe5dc..annevk/encode-set-names:c60ff34.html)
> Editorial: use specific names for encode sets

- url.bs
Remove “dead code” found through
https://github.com/w3c/web-platform-tests/issues/3018. (Note that the
API username/password setters are also no-ops for file URLs.)
***
[Preview](https://url.spec.whatwg.org/branch-snapshots/annevk/no-file-url-with-credentials/) | [Diff](https://s3.amazonaws.com/pr-preview/whatwg/url/6463c12..annevk/no-file-url-with-credentials:9dbbfaa.html)
> A file URL cannot have credentials

- url.bs
This is implemented by Firefox and Safari without much trouble. The
hope is that other browsers and user agents will follow suit.
Tests: https://github.com/w3c/web-platform-tests/pull/4771.
Fixes #239.
***
[Preview](https://url.spec.whatwg.org/branch-snapshots/annevk/Nontransitional/) | [Diff](https://s3.amazonaws.com/pr-preview/whatwg/url/2b3c864..annevk/Nontransitional:896aeff.html)
> Use Nontransitional_Processing for IDNA ToASCII

- url.bs
Fixes #253.
***
[Preview](https://url.spec.whatwg.org/branch-snapshots/annevk/hash-javascript/) | [Diff](https://s3.amazonaws.com/pr-preview/whatwg/url/6463c12..annevk/hash-javascript:b039de5.html)
> Remove javascript URL special case from the API

- url.bs
Summary of changes:
1. Fixes #258
2. Introduces <b>empty host</b> term for file and non-special URL's
3. Changes definition: <b>opaque host</b> is non-empty ASCII string
***
[Preview](https://s3.amazonaws.com/pr-preview/rmisev/url/empty-host-for-file.html) | [Diff](https://s3.amazonaws.com/pr-preview/whatwg/url/4bf85a0...rmisev:3893222.html)
> Use empty host for file URL's

- url.bs
As file URLs cannot have username/password/port we don’t want to allow
changing the scheme of a URL that contains one or more of those
components.
Fixes #259.
***
[Preview](https://url.spec.whatwg.org/branch-snapshots/annevk/protocol-setter/) | [Diff](https://s3.amazonaws.com/pr-preview/whatwg/url/5807b28...a8ed8d2.html)
> Restrict setting protocol to "file"

- url.bs
Fixes #266.
***
[Preview](https://url.spec.whatwg.org/branch-snapshots/annevk/ipv6-serializer/) | [Diff](https://s3.amazonaws.com/pr-preview/whatwg/url/8386c7a...4af559d.html)
> Clarify IPv6 serializer

- url.bs
This wasn’t used by the URL Standard directly so might as well go to
Fetch.
Change to Fetch: https://github.com/whatwg/fetch/issues/512.
Fixes #241.
***
[Preview](https://url.spec.whatwg.org/branch-snapshots/annevk/url-terminology/) | [Diff](https://s3.amazonaws.com/pr-preview/whatwg/url/7286569...2d8b4d7.html)
> Move some terminology to the Fetch Standard

- url.bs
It was wrong for MediaSource and MediaStream objects, which cannot be
serialized and deserialized, and it’s no longer necessary for Blob
objects as their state cannot be modified. (And it’s also out-of-date
as HTML now has serialization and deserialization operations.)
Fixes #277.
***
[Preview](https://url.spec.whatwg.org/branch-snapshots/annevk/remove-noop-clone/) | [Diff](https://s3.amazonaws.com/pr-preview/whatwg/url/8fb8684...66a3248.html)
> Remove StructuedClone call

- url.bs
Tests: https://github.com/w3c/web-platform-tests/pull/5195.
Closes #234 by superseding it. Fixes #232.
***
[Preview](https://url.spec.whatwg.org/branch-snapshots/annevk/file-url-path-slashes/) | [Diff](https://s3.amazonaws.com/pr-preview/whatwg/url/91cb2aa...91bcea4.html)
> URL: trim leading slashes of file URL paths

- url.bs
See https://github.com/whatwg/infra/pull/114 for the change to Infra.
***
[Preview](https://url.spec.whatwg.org/branch-snapshots/annevk/noncharacter/) | [Diff](https://s3.amazonaws.com/pr-preview/whatwg/url/6103e0a...19e6d7c.html)
> Editorial: use noncharacter from Infra

- url.bs
Fixes part of #282.
***
[Preview](https://url.spec.whatwg.org/branch-snapshots/annevk/ipv6/) | [Diff](https://s3.amazonaws.com/pr-preview/whatwg/url/91cb2aa...b41b65a.html)
> Editorial: remove labels from IPv6 parser

- url.bs
Changes:
1. Moves _ipv4Piece_ verification step right after the _ipv4Piece_ calculation. Because if the "_ipv4Piece_ > 255" verification returns failure, then no need to increase _pointer_.
2. Moves the last (8.) step to the outside of 6.5.5 loop. This lets drop `c is the EOF` check in this moved step, because loop stops on `EOF`. This obviously gives a better performance.
These changes are based on https://github.com/nodejs/node/pull/12315#discussion_r110858300 and https://github.com/nodejs/node/pull/12315#discussion_r110879264
***
[Preview](https://s3.amazonaws.com/pr-preview/rmisev/url/ipv4-in-ipv6-cleanup.html) | [Diff](https://s3.amazonaws.com/pr-preview/whatwg/url/703fcd0...rmisev:a1e1e80.html)
> IPv4 in IPv6 cleanup

- url.bs
- Use abstract-op to refer to ToASCII and ToUnicode
- Make all terms defined in another specification visible in "Terms defined by
reference" section
- Use biblio from SpecRef
- List all dependent standards in "Infrastructure" chapter
***
[Preview](https://s3.amazonaws.com/pr-preview/TimothyGu/url/ref-cleanup.html) | [Diff](https://s3.amazonaws.com/pr-preview/whatwg/url/488c459...TimothyGu:312d674.html)
> Editorial: cleanup references

- url.bs
Also simplifies the parser and removes mention of a nonexistent variable.
***
[Preview](https://s3.amazonaws.com/pr-preview/TimothyGu/url/form-urlencoded-infra.html) | [Diff](https://s3.amazonaws.com/pr-preview/whatwg/url/488c459...TimothyGu:542b196.html)
> Editorial: use Infra in a/x-www-form-urlencoded

- url.bs
Fixes #304
***
[Preview](https://s3.amazonaws.com/pr-preview/rmisev/url/file-state-304.html) | [Diff](https://s3.amazonaws.com/pr-preview/whatwg/url/488c459...rmisev:d671fd9.html)
> Fix windows drive letter handling in the file state

- url.bs
See https://github.com/whatwg/html/issues/2568 for discussion.
See https://github.com/whatwg/html/pull/2689 for the corresponding
change to the HTML Standard.
Closes #297.
***
[Preview](https://url.spec.whatwg.org/branch-snapshots/annevk/ascii-origin/) | [Diff](https://s3.amazonaws.com/pr-preview/whatwg/url/fe6b251...0098115.html)
> Make URL's origin return solely ASCII code points

- url.bs
***
[Preview](https://url.spec.whatwg.org/branch-snapshots/annevk/ipv6-more/) | [Diff](https://s3.amazonaws.com/pr-preview/whatwg/url/20c3257...a4f2eba.html)
> Refactor IPv6 in terms of lists

- url.bs
Fixes #135.
***
[Preview](https://url.spec.whatwg.org/branch-snapshots/zcorpan/webkiturl/) | [Diff](https://s3.amazonaws.com/pr-preview/whatwg/url/20c3257...62a0abf.html)
> Specify window.webkitURL as an alias to URL

- url.bs
As reported at
https://github.com/whatwg/url/issues/53#issuecomment-300718860 this is
causing issues in non-browser implementations.
***
[Preview](https://url.spec.whatwg.org/branch-snapshots/annevk/ToASCII-warning/) | [Diff](https://s3.amazonaws.com/pr-preview/whatwg/url/a622235...b5bb3d0.html)
> Address several IDNA issues

- url.bs
It appears identical to the earlier proposed revision 18 for the
purposes of the URL Standard.
Fixes #313.
***
[Preview](https://url.spec.whatwg.org/branch-snapshots/annevk/idna-r19/) | [Diff](https://s3.amazonaws.com/pr-preview/whatwg/url/072f639...abf9211.html)
> IDNA: UTS46 revision 19 is part of Unicode 10

- url.bs
Closes #327.
Tests: https://github.com/w3c/web-platform-tests/pull/6346
***
[Preview](https://s3.amazonaws.com/pr-preview/TimothyGu/url/scheme-port.html) | [Diff](https://s3.amazonaws.com/pr-preview/whatwg/url/b128ba9...TimothyGu:156b207.html)
> Normalize port after updating scheme

- url.bs
Fixes #333.
***
[Preview](https://url.spec.whatwg.org/branch-snapshots/annevk/urlsearchparams/) | [Diff](https://s3.amazonaws.com/pr-preview/whatwg/url/54fb58a...4f4e98f.html)
> Editorial: URLSearchParams always has an init parameter

- url.bs
Tests: …
Fixes #332.
***
[Preview](https://url.spec.whatwg.org/branch-snapshots/annevk/question-mark-and-urlsearchparams/) | [Diff](https://s3.amazonaws.com/pr-preview/whatwg/url/016f67f...152d224.html)
> Remove trailing ? when updating URLSearchParams

- url.bs
Fixes #315, fixes #322, and fixes #324.
***
[Preview](https://url.spec.whatwg.org/branch-snapshots/annevk/nits/) | [Diff](https://s3.amazonaws.com/pr-preview/whatwg/url/4315826...20c2cb9.html)
> Editorial: fix various nits

- url.bs
1. Introduces term: "a string starts with Windows drive letter". It simplifies the ***file state*** and solves the **remaining** problem (https://github.com/whatwg/url/issues/308).
2. Fixes https://github.com/whatwg/url/issues/303.
***
[Preview](https://s3.amazonaws.com/pr-preview/rmisev/url/file-slash-state-fix.html) | [Diff](https://s3.amazonaws.com/pr-preview/whatwg/url/19e0ffa...rmisev:32aa25e.html)
> Fix Windows drive letter handling in the file slash state

- url.bs
This is useful for https://github.com/whatwg/fetch/issues/234 and also simplifies the host parser a bit.
***
[Preview](https://url.spec.whatwg.org/branch-snapshots/annevk/string-percent-decode/) | [Diff](https://s3.amazonaws.com/pr-preview/whatwg/url/19e0ffa...a772a9e.html)
> Define percent decoding of strings

- url.bs
The web site does not work anymore.
Signed-off-by: Philippe Ombredanne <pombredanne@nexb.com>
***
<a href="https://s3.amazonaws.com/pr-preview/pombredanne/url-1/pull/352.html" title="Last updated on Nov 27, 2017, 2:26 PM GMT">Preview</a> | <a href="https://s3.amazonaws.com/pr-preview/whatwg/url/3b6b0b4...pombredanne:8746419.html" title="Last updated on Nov 27, 2017, 2:26 PM GMT">Diff</a>
> Remove Googlefight links

- url.bs
This is more consistent with other exports. Marked editorial as this also adds some HTTPS and fixes the spelling of implementers in a comment.
***
<a href="https://pr-preview.s3.amazonaws.com/whatwg/url/pull/356.html" title="Last updated on Nov 30, 2017, 9:13 AM GMT">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/whatwg/url/d9e4af8...17b022d.html" title="Last updated on Nov 30, 2017, 9:13 AM GMT">Diff</a>
> Editorial: export "urlencoded parser" for Fetch

- url.bs
Currently, we percent-encode characters in "fragment state" using the C0
control percent-encode set. Firefox encodes more than that, and it seems
reasonable to align around that behavior for reasons spelled out in #291
and the comments of #344.
This patch adds a new "fragment percent-encode set" which contains the
C0 control percent-encode set, along with:
* 0x22 (")
* 0x3C (<)
* 0x3E (>)
* 0x60 (`)
Closes #344.
***
[Preview](https://s3.amazonaws.com/pr-preview/mikewest/url/fragment-percent-encode.html) | [Diff](https://s3.amazonaws.com/pr-preview/whatwg/url/20c3257...mikewest:6c80db9.html)
> Percent-encode additional characters in "fragment state".

- url.bs
Add link to https://url.spec.whatwg.org/#concept-urlencoded-parser in
the "5.3. Hooks".
***
<a href="https://whatpr.org/url/362.html" title="Last updated on Dec 21, 2017, 7:40 AM GMT (09436ae)">Preview</a> | <a href="https://whatpr.org/url/362/0a7a094...09436ae.html" title="Last updated on Dec 21, 2017, 7:40 AM GMT (09436ae)">Diff</a>
> Editorial: add missing link

- url.bs
The URLs port in the tuple origin must be null, because port is not
specified in the input:
`blob:https://whatwg.org/d0360e2f-caee-469f-9a2f-87d5b0456f6f`
According to specification, if port is not specified or is default for
scheme, then URLs port is set to null:
https://url.spec.whatwg.org/#concept-url-port
https://url.spec.whatwg.org/#ref-for-default-port%E2%91%A0
***
<a href="https://whatpr.org/url/366.html" title="Last updated on Jan 9, 2018, 2:31 PM GMT (35d6bd5)">Preview</a> | <a href="https://whatpr.org/url/366/0d15b3f...35d6bd5.html" title="Last updated on Jan 9, 2018, 2:31 PM GMT (35d6bd5)">Diff</a>
> Editorial: fix port value in the origin's example

- .travis.yml
- CONTRIBUTING.md
- Makefile
- README.md
In particular:
* Add a CONTRIBUTING.md resource that points to the generic one.
* Adjust the Makefile and README to account for the shared deploy script.
* Make the README point to the shared maintainer guidelines.
> Meta: adopt more whatwg/meta guidelines

- url.bs
This works in Chrome, and I think it's what the spec says, but I don't see a matching test in web-platform-tests.
***
<a href="https://whatpr.org/url/376.html" title="Last updated on Mar 24, 2018, 9:32 PM GMT (c61c08b)">Preview</a> | <a href="https://whatpr.org/url/376/5fc4c4c...c61c08b.html" title="Last updated on Mar 24, 2018, 9:32 PM GMT (c61c08b)">Diff</a>
> Fix an example: new URL("https://domain/#frag") succeeds.

- .gitignore
- url.bs
This feature was removed in 2013 from Media Capture and Streams and is being removed from browsers (already gone in Safari).
Tests: https://github.com/w3c/web-platform-tests/pull/10515.
Fixes #380.
***
<a href="https://whatpr.org/url/381.html" title="Last updated on Apr 20, 2018, 4:41 PM GMT (ff13957)">Preview</a> | <a href="https://whatpr.org/url/381/a1b789c...ff13957.html" title="Last updated on Apr 20, 2018, 4:41 PM GMT (ff13957)">Diff</a>
> URL's object can no longer be a MediaStream

- url.bs
This fixes https://github.com/whatwg/html/issues/3648.
***
<a href="https://whatpr.org/url/384.html" title="Last updated on May 8, 2018, 9:05 AM GMT (eeea22e)">Preview</a> | <a href="https://whatpr.org/url/384/5c0d2ec...eeea22e.html" title="Last updated on May 8, 2018, 9:05 AM GMT (eeea22e)">Diff</a>
> Remove 'type' from from data entries.

- url.bs
If the input to the URL parser contains code points outside the non-UTF-8 encoding's value space and the URL parser was invoked using a non-UTF-8 encoding, then those code points end up as &#...;.
The problem is that &, #, and ; are also URL separators, but the previous algorithm would only encode #. This ensures that & and ; are also encoded, as some browsers already do, but only if they came about as the result of the encode operation.
Tests: [we need to make a number of test changes for this]
***
<a href="https://whatpr.org/url/386.html" title="Last updated on May 23, 2018, 6:41 AM GMT (2518aa4)">Preview</a> | <a href="https://whatpr.org/url/386/acc2bf4...2518aa4.html" title="Last updated on May 23, 2018, 6:41 AM GMT (2518aa4)">Diff</a>
> Change query state slightly to better deal with non-UTF-8 encodings

- url.bs
HTML invokes it without a second argument and expects it to special by default.
***
<a href="https://whatpr.org/url/388.html" title="Last updated on May 30, 2018, 6:04 AM GMT (04842ce)">Preview</a> | <a href="https://whatpr.org/url/388/f0e4390...04842ce.html" title="Last updated on May 30, 2018, 6:04 AM GMT (04842ce)">Diff</a>
> Give host parser a suitable default for the HTML Standard

- url.bs
This patch is another attempt at whatwg/url#72, and defers most of the actual work to the
algorithms defined at https://publicsuffix.org/list/.
I wonder if this is something we should expose on `URL` objects? I thikn @hillbrad was asking for it a looong time ago, but I don't know if he still has use cases.
***
<a href="https://whatpr.org/url/391.html" title="Last updated on Jun 4, 2018, 12:45 PM GMT (8828de3)">Preview</a> | <a href="https://whatpr.org/url/391/f0e4390...8828de3.html" title="Last updated on Jun 4, 2018, 12:45 PM GMT (8828de3)">Diff</a>
> Define hosts' public suffix and registrable domain.

- url.bs
Tests: https://github.com/web-platform-tests/wpt/pull/11389
Fixes https://github.com/whatwg/url/issues/348
***
<a href="https://whatpr.org/url/395.html" title="Last updated on Jun 6, 2018, 8:18 PM GMT (97ac46a)">Preview</a> | <a href="https://whatpr.org/url/395/ac532ae...97ac46a.html" title="Last updated on Jun 6, 2018, 8:18 PM GMT (97ac46a)">Diff</a>
> percent-encode ' in queries of URLs with special schemes

- url.bs
As mentioned in https://github.com/whatwg/url/issues/400#issuecomment-406900069, the IDNA spec previously used Nontransitional Processing unconditionally in the ToUnicode algorithm. However, a recent spec change changed the ToUnicode algorithm to accept a boolean flag called *Transitional_Processing*, which allows the user to choose between Transitional and Nontransitional processing. This makes it so that the [domain to ASCII](https://url.spec.whatwg.org/#concept-domain-to-ascii), [domain to Unicode]( https://url.spec.whatwg.org/#concept-domain-to-unicode) algorithms, and [valid domain](https://url.spec.whatwg.org/#valid-domain) steps explicitly state the value for the *Transitional_Processing* flag, which preserves the previous behavior of using Nontransitional processing.
It also …
> Preserve use of Nontransitional processing for IDNA

- url.bs
This is the only part of the URL Serializer's output that wasn't already
specified to be ASCII.
I believe domains are always ASCII because:
* The URL Parser always sets a URL's host to the result of the host
parser.
* The host parser on things other than IPv4, IPv6, and opaque hosts
(i.e. "domains") returns |asciiDomain|, the result of 'domain to
ASCII'.
* The URL.host setter passes its input through the URL parser.
I care because I want to know the right way to convert the result of the URL Serializer to a [header's value](https://fetch.spec.whatwg.org/#concept-header-value), a byte sequence.
***
<a href="https://whatpr.org/url/409.html" title="Last updated on Aug 3, 2018, 8:45 PM GMT (ff75aba)">Preview</a> | <a href="https://whatpr.org/url/409/6800342...ff75aba.html" title="Last updated …
> Specify that domains are ASCII strings.

- README.md
As discussed over email, there are a bunch of really helpful resources for implementors and editors which aren't findable from this repo itself.
Adds links to:
* [wpt.fyi](https://wpt.fyi/results/url)
* [jsdom/whatwg-url](https://github.com/jsdom/whatwg-url)
* [Live URL Viewer](https://jsdom.github.io/whatwg-url/)
> README: Added links to WPT dashboard, jsdom/whatwg-url and Live URL Viewer.

- url.bs
This fixes #290, fixes #127, fixes w3c/FileAPI#20 and fixes w3c/FileAPI#63.
The only observable change here is the origin for blob URLs created in unique origins (which is only observable indirectly by trying to fetch such URLs), and tests for that already exist in https://w3c-test.org/FileAPI/url/sandboxed-iframe.html.
***
<a href="https://whatpr.org/url/371.html" title="Last updated on Jan 11, 2019, 9:19 AM UTC (8b426c4)">Preview</a> | <a href="https://whatpr.org/url/371/07ecb3b...8b426c4.html" title="Last updated on Jan 11, 2019, 9:19 AM UTC (8b426c4)">Diff</a>
> Use definitions in FileAPI spec to resolve blob URLs and their origins.

- url.bs
This is my first attempt at fixing #429.
***
<a href="https://whatpr.org/url/430.html" title="Last updated on Feb 11, 2019, 1:15 PM UTC (046ebf1)">Preview</a> | <a href="https://whatpr.org/url/430/d2ef633...046ebf1.html" title="Last updated on Feb 11, 2019, 1:15 PM UTC (046ebf1)">Diff</a>
> Suggest use of origin in warning text (Fixes #429)

- url.bs
I added this fact in the wrong place in #409: it ought to be on the definition of the [URL serializer](https://url.spec.whatwg.org/#concept-url-serializer) and not just [one of the uses](https://url.spec.whatwg.org/#ref-for-concept-url-serializer①). (I care because I just wasted a bit of time double-checking that it was true.)
I don't feel strongly about the `Assert` at the bottom of the algorithm.
***
<a href="https://whatpr.org/url/428.html" title="Last updated on Feb 7, 2019, 9:05 PM UTC (4d5ca88)">Preview</a> | <a href="https://whatpr.org/url/428/d2ef633...4d5ca88.html" title="Last updated on Feb 7, 2019, 9:05 PM UTC (4d5ca88)">Diff</a>
> Be clearer that URL serialization returns an ASCII string.

- url.bs
Fixes #342
***
<a href="https://whatpr.org/url/453.html" title="Last updated on Oct 17, 2019, 7:09 PM UTC (1dba2e1)">Preview</a> | <a href="https://whatpr.org/url/453/5f8576e...1dba2e1.html" title="Last updated on Oct 17, 2019, 7:09 PM UTC (1dba2e1)">Diff</a>
> Remove gopher from list of special schemes

- url.bs
After #453 the "gopher:" is not special anymore.
According to https://github.com/web-platform-tests/wpt/pull/19770 an intention is that gopher's URL's origin would be opaque (null).
***
<a href="https://whatpr.org/url/454.html" title="Last updated on Oct 18, 2019, 5:25 PM UTC (15c823b)">Preview</a> | <a href="https://whatpr.org/url/454/d589670...15c823b.html" title="Last updated on Oct 18, 2019, 5:25 PM UTC (15c823b)">Diff</a>
> Remove gopher's case from origin's algorithm

- url.bs
Closes #449. Partially addresses #448.
---
Marking "do not merge yet" because the build will fail until the HTML pull request is merged.
***
<a href="https://whatpr.org/url/457.html" title="Last updated on Nov 20, 2019, 5:39 PM UTC (51f8e2f)">Preview</a> | <a href="https://whatpr.org/url/457/7ae1c69...51f8e2f.html" title="Last updated on Nov 20, 2019, 5:39 PM UTC (51f8e2f)">Diff</a>
> Let HTML handle the "same site" definition

- url.bs
The ASCII prefix is xn--, not xn-. Also add an example where the public suffix is null as callers used to forget about it.
Closes #471.
***
<a href="https://whatpr.org/url/472.html" title="Last updated on Mar 27, 2020, 5:50 AM UTC (07b0ed7)">Preview</a> | <a href="https://whatpr.org/url/472/0ce82da...07b0ed7.html" title="Last updated on Mar 27, 2020, 5:50 AM UTC (07b0ed7)">Diff</a>
> Correct and add to PSL examples

- url.bs
This has come up enough that it's worth mentioning explicitly.
Closes #233.
***
<a href="https://whatpr.org/url/481.html" title="Last updated on Apr 26, 2020, 1:26 PM UTC (e2dbe5a)">Preview</a> | <a href="https://whatpr.org/url/481/980ba89...e2dbe5a.html" title="Last updated on Apr 26, 2020, 1:26 PM UTC (e2dbe5a)">Diff</a>
> Note that the address bar is out-of-scope

- url.bs
Tests: ...
Fixes #440.
(Note that I think we should make all states an explicit ordered list for clarity. Because of that I added it here, despite it only containing one step.)
* Chrome
* Firefox
* Safari
* https://github.com/web-platform-tests/wpt/pull/23256
* Chrome: https://bugs.chromium.org/p/chromium/issues/detail?id=1075492
* Firefox: (probably not needed, but need tests to confirm)
* Safari: (probably not needed, but need tests to confirm)
***
<a href="https://whatpr.org/url/486.html" title="Last updated on Apr 27, 2020, 9:40 AM UTC (5d63a5c)">Preview</a> | <a href="https://whatpr.org/url/486/980ba89...5d63a5c.html" title="Last updated on Apr 27, 2020, 9:40 AM UTC (5d63a5c)">Diff</a>
> Remove U+0000 case in the fragment state

- url.bs
Fixes #295.
@GPHemsley @Hixie, what do you think?
***
<a href="https://whatpr.org/url/482.html" title="Last updated on Apr 28, 2020, 6:17 AM UTC (3f408d6)">Preview</a> | <a href="https://whatpr.org/url/482/980ba89...3f408d6.html" title="Last updated on Apr 28, 2020, 6:17 AM UTC (3f408d6)">Diff</a>
> Clarify double-dot path segment parsing

- url.bs
Closes #396.
***
<a href="https://whatpr.org/url/484.html" title="Last updated on Apr 26, 2020, 3:58 PM UTC (695c968)">Preview</a> | <a href="https://whatpr.org/url/484/980ba89...695c968.html" title="Last updated on Apr 26, 2020, 3:58 PM UTC (695c968)">Diff</a>
> Clarify output of PSL is in A-Labels

- url.bs
Helps with #337.
Next is taking @TimothyGu's work and give the API a similar table...
***
<a href="https://whatpr.org/url/489.html" title="Last updated on May 5, 2020, 8:08 AM UTC (4e48520)">Preview</a> | <a href="https://whatpr.org/url/489/d8fb1a4...4e48520.html" title="Last updated on May 5, 2020, 8:08 AM UTC (4e48520)">Diff</a>
> Clarify how URL strings map to URL components via table

- url.bs
Closes #437.
(It does strike me that there are some patterns here that might warrant abstraction.)
***
<a href="https://whatpr.org/url/494.html" title="Last updated on May 5, 2020, 3:41 PM UTC (fd7a344)">Preview</a> | <a href="https://whatpr.org/url/494/1bb45ce...fd7a344.html" title="Last updated on May 5, 2020, 3:41 PM UTC (fd7a344)">Diff</a>
> Fix validity for opaque hosts

- url.bs
Closes #18. Follow-up: #491.
I should probably add some editor warnings in case we ever change one of these four enumerations.
***
<a href="https://whatpr.org/url/495.html" title="Last updated on May 6, 2020, 10:20 AM UTC (c7ada96)">Preview</a> | <a href="https://whatpr.org/url/495/96ead3f...c7ada96.html" title="Last updated on May 6, 2020, 10:20 AM UTC (c7ada96)">Diff</a>
> Enumerate differences between URLSearchParams and search

- url.bs
The empty host is not allowed in special non-"file" URLs, but
`domain to ASCII` result can be the empty string, even if the
input is not empty, for example:
* the input consists entirely of IDNA ignored code points;
* the input is `xn--`.
The `domain to ASCII` do not fail when it is called from `host parser`,
because `VerifyDnsLength` is false.
So we need additional check after it.
An interesting case is with file URLS, as empty host is allowed. But most
browsers report failure as well. I tested URLs with the `U+00AD`
percent encoded in host:
| URL               | Chrome    | Firefox     | Safari    |
|-------------------|-----------|-------------|-----------|
| `file://%C2%AD/p` | TypeError | `file:///p` | TypeError |
| `http://%C2%AD/p` | TypeError | TypeError   | TypeError |
Note. To …
> Verify domain is not empty after "domain to ASCII"

- url.bs
See 8315a809988c30a54f0f08048d027119ea77612c for where this was initially added.
***
<a href="https://whatpr.org/url/499.html" title="Last updated on May 7, 2020, 8:33 AM UTC (d4e48da)">Preview</a> | <a href="https://whatpr.org/url/499/cceb435...d4e48da.html" title="Last updated on May 7, 2020, 8:33 AM UTC (d4e48da)">Diff</a>
> Omitted part of the C0 controls by mistake

- url.bs
Helps with #296.
***
<a href="https://whatpr.org/url/500.html" title="Last updated on May 8, 2020, 6:23 AM UTC (254b3c7)">Preview</a> | <a href="https://whatpr.org/url/500/c76c15f...254b3c7.html" title="Last updated on May 8, 2020, 6:23 AM UTC (254b3c7)">Diff</a>
> Editorial: minor tweaks to percent-encoded bytes

- url.bs
Helps with #504.
(I'll double check with whatwg-url that this is okay in a bit.)
***
<a href="https://whatpr.org/url/509.html" title="Last updated on May 11, 2020, 6:07 AM UTC (f44e356)">Preview</a> | <a href="https://whatpr.org/url/509/68aad5d...f44e356.html" title="Last updated on May 11, 2020, 6:07 AM UTC (f44e356)">Diff</a>
> Editorial: deduplicate the relative state

- url.bs
See https://github.com/heycam/webidl/issues/730.
This also goes back to using uppercase URL for associated concepts and ensures URLSearchParams's update mechanism accounts for there not being an associated URL object.
(This is basically editorial, except for that null pointer fix.)
***
<a href="https://whatpr.org/url/507.html" title="Last updated on May 11, 2020, 6:18 PM UTC (3d5e5bd)">Preview</a> | <a href="https://whatpr.org/url/507/68aad5d...3d5e5bd.html" title="Last updated on May 11, 2020, 6:18 PM UTC (3d5e5bd)">Diff</a>
> Align with a more modern IDL style

- url.bs
And use it internally. This is also an initial step for #369.
If reviewers have thoughts on how to resolve #296 that'd be appreciated. Renaming things is in scope for this PR modulo the caveats mentioned there. Resolving to continue using the existing names is also fine with me.
***
<a href="https://whatpr.org/url/503.html" title="Last updated on May 12, 2020, 7:23 AM UTC (d0fc83f)">Preview</a> | <a href="https://whatpr.org/url/503/ea3b75d...d0fc83f.html" title="Last updated on May 12, 2020, 7:23 AM UTC (d0fc83f)">Diff</a>
> Add string UTF-8 percent encode

- url.bs
(Note that this depends on #503 landing first.)
@rmisev @domenic @mgiuca @mkgl what do you think? Worth doing?
***
<a href="https://whatpr.org/url/508.html" title="Last updated on May 13, 2020, 2:25 PM UTC (1ad3c60)">Preview</a> | <a href="https://whatpr.org/url/508/8e1c9e3...1ad3c60.html" title="Last updated on May 13, 2020, 2:25 PM UTC (1ad3c60)">Diff</a>
> Editorial: use an encode set in the query state

- url.bs
This reverts commit bc7ac863aead17d6447133eb0de89a88bd6801f1.
When I started looking at what it would take to do this for application/x-www-form-urlencoded I realize that this is not editorial at all and in fact changes behavior.
If the input is U+0080 that would become 0xC2 0x80 when UTF-8 encoded. We then turn that into U+00C2 U+0080. We then UTF-8 percent-encode that, creating %C3%82%C2%80 rather than %C2%80.
I think the only way to go here is to have a byte version of UTF-8 percent-encoding. I guess that could still use the code point sets but it would be a bit messy/weird?
***
<a href="https://whatpr.org/url/517.html" title="Last updated on May 13, 2020, 4:00 PM UTC (e236f60)">Preview</a> | <a href="https://whatpr.org/url/517/bc7ac86...e236f60.html" title="Last updated on May 13, …
> Revert "Editorial: use an encode set in the query state"

- url.bs
> Considering <> seem to be forbidden in two browsers, we should consider making them forbidden too. The list is testable through new URL('http://</').href.
This PR add `<` and `>` to `Host miscellaneous`, Close #458
***
<a href="https://whatpr.org/url/459.html" title="Last updated on May 7, 2020, 5:04 PM UTC (605aa0f)">Preview</a> | <a href="https://whatpr.org/url/459/3703f92...605aa0f.html" title="Last updated on May 7, 2020, 5:04 PM UTC (605aa0f)">Diff</a>
> Forbid < and > in hosts

- url.bs
Maybe helps with #504, though this is much less convincing than #509 I think.
I also noticed there is not good coverage for file base URLs.
***
<a href="https://whatpr.org/url/512.html" title="Last updated on May 11, 2020, 6:59 AM UTC (c5b2321)">Preview</a> | <a href="https://whatpr.org/url/512/68aad5d...c5b2321.html" title="Last updated on May 11, 2020, 6:59 AM UTC (c5b2321)">Diff</a>
> Editorial: attempt to deduplicate the file state

- url.bs
Spotted in https://github.com/whatwg/url/pull/502.
***
<a href="https://whatpr.org/url/519.html" title="Last updated on May 18, 2020, 9:00 AM UTC (e540eac)">Preview</a> | <a href="https://whatpr.org/url/519/cb9c97f...e540eac.html" title="Last updated on May 18, 2020, 9:00 AM UTC (e540eac)">Diff</a>
> Define upper limit of a URL-port string

- url.bs
This switches the URL parser's query state and the application/x-www-form-urlencoded's serializer to also use percent-encode sets.
Closes #411.
I'll see about writing a whatwg-url patch.
***
<a href="https://whatpr.org/url/518.html" title="Last updated on May 20, 2020, 5:18 AM UTC (91bead4)">Preview</a> | <a href="https://whatpr.org/url/518/19494f1...91bead4.html" title="Last updated on May 20, 2020, 5:18 AM UTC (91bead4)">Diff</a>
> Editorial: make everything use percent-encode sets

- url.bs
Complements https://github.com/whatwg/html/pull/5524. 
Closes #369.
***
<a href="https://whatpr.org/url/513.html" title="Last updated on Jun 26, 2020, 5:55 AM UTC (7c6cae3)">Preview</a> | <a href="https://whatpr.org/url/513/e5334dd...7c6cae3.html" title="Last updated on Jun 26, 2020, 5:55 AM UTC (7c6cae3)">Diff</a>
> Add the component percent-encode set

- url.bs
Adjust the URL serializer so it does not output something which during the next parse operation would yield a host.
whatwg-url: https://github.com/jsdom/whatwg-url/pull/148
Tests: ...
Fixes #415.
@zealousidealroll what do you think?
* …
* …
* …
* Chrome: …
* Firefox: …
* Node.js: …
* Safari: …
***
<a href="https://whatpr.org/url/505.html" title="Last updated on Aug 23, 2020, 4:22 PM UTC (c3c7a82)">Preview</a> | <a href="https://whatpr.org/url/505/e5334dd...c3c7a82.html" title="Last updated on Aug 23, 2020, 4:22 PM UTC (c3c7a82)">Diff</a>
> Non-special URLs were not idempotent

- url.bs
Fixes #545.
***
<a href="https://whatpr.org/url/546.html" title="Last updated on Sep 29, 2020, 7:22 AM UTC (8c58e3c)">Preview</a> | <a href="https://whatpr.org/url/546/83adf0c...8c58e3c.html" title="Last updated on Sep 29, 2020, 7:22 AM UTC (8c58e3c)">Diff</a>
> Correct percent-encode example and add one

- url.bs
Changes to file URL path normalization as proposed in #405.  
Summary:
Applicable only to file URLs:
- Leading empty path segements are no longer removed. 
- If absent, the host is copied from the base URL,
- Otherwise the host is preserved with one exception:
- If the host is `localhost` then it is set to the empty string. 
Intends to close #405 and #302. 
- Tests: https://github.com/web-platform-tests/wpt/pull/25716. 
- Reference implementation: https://github.com/jsdom/whatwg-url/pull/170.
***
<a href="https://whatpr.org/url/544.html" title="Last updated on Sep 29, 2020, 9:54 AM UTC (3469a42)">Preview</a> | <a href="https://whatpr.org/url/544/83adf0c...3469a42.html" title="Last updated on Sep 29, 2020, 9:54 AM UTC (3469a42)">Diff</a>
> Changes to file URL path normalization

- url.bs
Fixes issue by ensuring file URL's host is not null.
Changes:
- Set url's host to the empty string at the start of file state.
- Updates URL parser and serializer accordingly.
Fixes: https://github.com/whatwg/url/issues/549
* …
* …
* https://github.com/web-platform-tests/wpt/pull/25989
* Chrome: no bugs
* Firefox: no bugs
* Safari: no bugs
***
<a href="https://whatpr.org/url/550.html" title="Last updated on Oct 7, 2020, 9:56 AM UTC (bcad0c4)">Preview</a> | <a href="https://whatpr.org/url/550/47efa00...bcad0c4.html" title="Last updated on Oct 7, 2020, 9:56 AM UTC (bcad0c4)">Diff</a>
> Fix file URL reparse issue

- url.bs
* Firefox
* Safari
* https://github.com/web-platform-tests/wpt/pull/26158
* Chrome: https://bugs.chromium.org/p/chromium/issues/detail?id=1140965
* Firefox: https://bugzilla.mozilla.org/show_bug.cgi?id=1671908
* Safari: https://bugs.webkit.org/show_bug.cgi?id=218046
***
<a href="https://whatpr.org/url/558.html" title="Last updated on Nov 2, 2020, 9:43 AM UTC (38f6ae8)">Preview</a> | <a href="https://whatpr.org/url/558/a19495e...38f6ae8.html" title="Last updated on Nov 2, 2020, 9:43 AM UTC (38f6ae8)">Diff</a>
> Refactor query state to operate on a buffer

- url.bs
Closes #569.
* This is a spec bug introduced in #558; all browsers do the right thing here.
* This is tested in [https://github.com/web-platform-tests/wpt/blob/master/url/url-searchparams.any.js], for example.
* N/A
***
<a href="https://whatpr.org/url/570.html" title="Last updated on Jan 4, 2021, 10:47 AM UTC (d519278)">Preview</a> | <a href="https://whatpr.org/url/570/2ce4938...d519278.html" title="Last updated on Jan 4, 2021, 10:47 AM UTC (d519278)">Diff</a>
> Fix handling of spaceAsPlus in percent-encode after encoding

- url.bs
Thanks Infra!
***
[PR Preview](https://github.com/tobie/pr-preview#pr-preview) failed to build. _(Last tried on Feb 1, 2021, 5:49 PM UTC)_.
<details>
<summary>More</summary>
PR Preview relies on a number of web services to run. There seems to be an issue with the following one:
:rotating_light: [CSS Spec Preprocessor](https://api.csswg.org/bikeshed/) - CSS Spec Preprocessor is the web service used to build Bikeshed specs.
:link: [Related URL](https://api.csswg.org/bikeshed/?url=https%3A%2F%2Fraw.githubusercontent.com%2Fwhatwg%2Furl%2Fc55bf428c077e37cd954f32af2f2bc552deea74b%2Furl.bs&force=1&md-status=LS-PR&md-Text-Macro=PR-NUMBER%20575)
```
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>500 Internal Server Error</title>
</head><body>
<h1>Internal Server Error</h1> …
```
> Editorial: algorithms can now have default argument values

- url.bs
Users require guidance about how to encode data as an opaque host string - for instance, it is common to want to encode a filesystem path as a hostname to create an `http+unix:` URL.
Moreover, the `host`/`hostname` setter is unique in that it will fail if the new value contains forbidden host code units, unlike other setters which automatically percent-encode any invalid characters, so it is important that users correctly encode the new value in order for the operation to succeed.
I would like to advise users to encode their hostnames with the component encode-set, and it would be nice if there was an explicit mention in the standard to back this advice up - as there is for the path, query and fragment.
***
<a href="https://whatpr.org/url/584.html" title="Last updated on Mar 3, 2021, …
> [Editorial] Guarantee that strings encoded with the component encode-set are valid opaque host strings.

- url.bs
This fixes issue #559.
* …
* …
* …
* Chrome: …
* Firefox: …
* Safari: …
***
<a href="https://whatpr.org/url/589.html" title="Last updated on Mar 17, 2021, 4:53 PM UTC (899e68a)">Preview</a> | <a href="https://whatpr.org/url/589/6c66d6c...899e68a.html" title="Last updated on Mar 17, 2021, 4:53 PM UTC (899e68a)">Diff</a>
> Forbid | in URL hosts

- url.bs
Many implementations currently skip ToASCII if domain is ASCII-only, but as discovered in https://github.com/whatwg/url/issues/267 and https://github.com/whatwg/url/pull/309#issuecomment-301405332, this can result in some undesirable behavior. Adding a note prevents implementors from making the mistake of thinking ToASCII is a no-op if the input is ASCII, and also provides a recommendation on how to properly optimize the ToASCII step.
***
<a href="https://whatpr.org/url/598.html" title="Last updated on May 19, 2021, 1:58 AM UTC (8dc2610)">Preview</a> | <a href="https://whatpr.org/url/598/0915d88...8dc2610.html" title="Last updated on May 19, 2021, 1:58 AM UTC (8dc2610)">Diff</a>
> Editorial: Add note about when ToASCII = ASCII lowercase

- url.bs
Fixes #601.
* Firefox (already implemented)
* Safari (already implemented)
* https://github.com/web-platform-tests/wpt/pull/29021
* Chrome: https://crbug.com/1018721
* Node.js: https://github.com/nodejs/node/issues/38710
* whatwg-url: https://github.com/jsdom/whatwg-url/pull/183
***
<a href="https://whatpr.org/url/604.html" title="Last updated on May 19, 2021, 4:17 PM UTC (974b094)">Preview</a> | <a href="https://whatpr.org/url/604/8c24e54...974b094.html" title="Last updated on May 19, 2021, 4:17 PM UTC (974b094)">Diff</a>
> Make hostname state return early if a port is given

- url.bs
In particular, only use them when the URL parser is invoked without an override state.
***
<a href="https://whatpr.org/url/605.html" title="Last updated on May 19, 2021, 6:51 PM UTC (3e1652b)">Preview</a> | <a href="https://whatpr.org/url/605/ec96993...3e1652b.html" title="Last updated on May 19, 2021, 6:51 PM UTC (3e1652b)">Diff</a>
> Emit validation errors more consistently

- url.bs
After whatwg/html#6287, no callers are left which invoke the `application/x-www-form-urlencoded` serializer with file values.
Do not merge before whatwg/html#6287.
***
<a href="https://whatpr.org/url/585.html" title="Last updated on Feb 27, 2021, 12:40 PM UTC (ef7153f)">Preview</a> | <a href="https://whatpr.org/url/585/557567c...ef7153f.html" title="Last updated on Feb 27, 2021, 12:40 PM UTC (ef7153f)">Diff</a>
> Editorial: remove support for files in the urlencoded serialization

- url.bs
This decreases the delta between relative and file states.
***
<a href="https://whatpr.org/url/613.html" title="Last updated on Jun 6, 2021, 9:51 AM UTC (3da759d)">Preview</a> | <a href="https://whatpr.org/url/613/6d4669a...3da759d.html" title="Last updated on Jun 6, 2021, 9:51 AM UTC (3da759d)">Diff</a>
> Editorial: Restate shorten and use it more

- url.bs
This is aimed at addressing issue #560.  If the last component of a URL's hostname is numeric, it's parsed as an IPv4 hostname, and if that fails, the URL's host is rejected.  e.g., "foo.0", "bar.0.09", "a.1.2.0x.", "1.2.3.4.5" were all previously considered valid non-IPv4 hostnames, but are now all rejected.  See #560 for more discussion on why allowing these are potentially concerning.
* Chrome
* FireFox
* https://github.com/web-platform-tests/wpt/pull/29666
* Chrome: https://crbug.com/1237032
* Firefox: https://bugzilla.mozilla.org/show_bug.cgi?id=1723456
* Safari: https://bugs.webkit.org/show_bug.cgi?id=228826
***
<a href="https://whatpr.org/url/619.html" title="Last updated on Aug 5, 2021, …
> Reject non-IPv4 hostnames that end in numbers.

- url.bs
Depends on https://github.com/whatwg/infra/pull/401
***
<a href="https://whatpr.org/url/649.html" title="Last updated on Sep 9, 2021, 10:28 PM UTC (0aa39b7)">Preview</a> | <a href="https://whatpr.org/url/649/7071c49...0aa39b7.html" title="Last updated on Sep 9, 2021, 10:28 PM UTC (0aa39b7)">Diff</a>
> Editorial: use Infra substring operations

- url.bs
Attempt at resolving #627 and #319
* Chrome (Presumably - See linked issue)
* WebKit (Presumably - See linked issue)
* https://github.com/web-platform-tests/wpt/pull/32524
* Chrome: https://bugs.chromium.org/p/chromium/issues/detail?id=1291564
* Firefox: https://bugzilla.mozilla.org/show_bug.cgi?id=1752320
* Safari: https://bugs.webkit.org/show_bug.cgi?id=235709
* Deno: https://github.com/denoland/deno/issues/13509
* Node.js: https://github.com/nodejs/node/issues/41717
***
<a href="https://whatpr.org/url/685.html" title="Last updated on Jan 28, 2022, 8:59 AM UTC (3229929)">Preview</a> | <a href="https://whatpr.org/url/685/68dc61c...3229929.html" title="Last updated on Jan 28, 2022, 8:59 AM UTC …
> Split forbidden host/domain code points, and add all C0 controls and add U+007F to the latter

- url.bs
The full IDNA algorithm lowercases before checking the `"xn--"` prefix, so any implementors fast-pathing ASCII domains should make sure that they check for it case-insensitively.
Added tests:
* https://github.com/web-platform-tests/wpt/pull/32177
***
<a href="https://whatpr.org/url/678.html" title="Last updated on Jan 14, 2022, 12:48 PM UTC (4f43025)">Preview</a> | <a href="https://whatpr.org/url/678/f787850...4f43025.html" title="Last updated on Jan 14, 2022, 12:48 PM UTC (4f43025)">Diff</a>
> [Editorial] Correct the note about the IDNA fast-path for ASCII domains

- url.bs
I’ve been setting bad precedents.
***
<a href="https://whatpr.org/url/686.html" title="Last updated on Feb 11, 2022, 6:17 PM UTC (8455f6a)">Preview</a> | <a href="https://whatpr.org/url/686/a6c5f19...8455f6a.html" title="Last updated on Feb 11, 2022, 6:17 PM UTC (8455f6a)">Diff</a>
> Editorial: address some minor nits

- url.bs
Closes #690.
***
<a href="https://whatpr.org/url/691.html" title="Last updated on Apr 25, 2022, 8:19 PM UTC (52d7702)">Preview</a> | <a href="https://whatpr.org/url/691/9a83e25...52d7702.html" title="Last updated on Apr 25, 2022, 8:19 PM UTC (52d7702)">Diff</a>
> Add more examples of opaque hosts

- url.bs
Also update the PSL algorithm reference. 
Fixes #692 and fixes #693.
(This depends on https://github.com/whatwg/infra/pull/446.)
***
<a href="https://whatpr.org/url/694.html" title="Last updated on May 3, 2022, 8:06 AM UTC (371b108)">Preview</a> | <a href="https://whatpr.org/url/694/3bc2e34...371b108.html" title="Last updated on May 3, 2022, 8:06 AM UTC (371b108)">Diff</a>
> Account for a trailing dot in public suffix and registrable domain

- url.bs
Recently HTML introduced a for="site" version, so we need to be more specific.
Blocks #700.
***
<a href="https://whatpr.org/url/701.html" title="Last updated on Aug 15, 2022, 4:27 AM UTC (fbdfcb3)">Preview</a> | <a href="https://whatpr.org/url/701/4ef812c...fbdfcb3.html" title="Last updated on Aug 15, 2022, 4:27 AM UTC (fbdfcb3)">Diff</a>
> Meta: fix "same site" reference

- url.bs
This change mainly removes the no-backref class that no longer has any meaning.
***
<a href="https://whatpr.org/url/718.html" title="Last updated on Nov 23, 2022, 9:45 AM UTC (d5c3679)">Preview</a> | <a href="https://whatpr.org/url/718/a46cb91...d5c3679.html" title="Last updated on Nov 23, 2022, 9:45 AM UTC (d5c3679)">Diff</a>
> Editorial: address a couple minor nits

- url.bs
1. No need for optional arguments given the number of callers.
2. Call Unicode ToUnicode from a single place.
***
<a href="https://whatpr.org/url/720.html" title="Last updated on Dec 2, 2022, 9:49 AM UTC (496a0c6)">Preview</a> | <a href="https://whatpr.org/url/720/48f1e79...496a0c6.html" title="Last updated on Dec 2, 2022, 9:49 AM UTC (496a0c6)">Diff</a>
> Editorial: minor cleanup around the internal IDNA algorithms

- url.bs
Given the existing callers these are not normative changes, but there was definitely a lack of clarity.
Closes https://github.com/web-platform-tests/wpt/issues/37010.
***
<a href="https://whatpr.org/url/719.html" title="Last updated on Dec 5, 2022, 10:51 AM UTC (307bc99)">Preview</a> | <a href="https://whatpr.org/url/719/48f1e79...307bc99.html" title="Last updated on Dec 5, 2022, 10:51 AM UTC (307bc99)">Diff</a>
> Editorial: clarify the types of strings algorithms take and return

- url.bs
Fixes whatwg/url#712
* …
* …
* …
* Chromium: …
* Gecko: …
* WebKit: …
* Deno: …
* Node.js: …
***
<a href="https://whatpr.org/url/721.html" title="Last updated on Dec 8, 2022, 7:25 PM UTC (6586f35)">Preview</a> | <a href="https://whatpr.org/url/721/3b3ceb3...6586f35.html" title="Last updated on Dec 8, 2022, 7:25 PM UTC (6586f35)">Diff</a>
> Clarify goals wording

- url.bs
Closes #595.
***
<a href="https://whatpr.org/url/666.html" title="Last updated on Oct 21, 2021, 11:44 AM UTC (568433f)">Preview</a> | <a href="https://whatpr.org/url/666/61949aa...568433f.html" title="Last updated on Oct 21, 2021, 11:44 AM UTC (568433f)">Diff</a>
***
<a href="https://whatpr.org/url/666.html" title="Last updated on Dec 9, 2022, 10:26 AM UTC (c3ade50)">Preview</a> | <a href="https://whatpr.org/url/666/15a2dc9...c3ade50.html" title="Last updated on Dec 9, 2022, 10:26 AM UTC (c3ade50)">Diff</a>
> Editorial: clarify URL validity

- url.bs
Missed in d2ef633869b3f31d8c7e3bb76602400e4d2c126c. (And DOM was there I suspect for "context object" which is now "this" in Web IDL.)
***
<a href="https://whatpr.org/url/723.html" title="Last updated on Dec 9, 2022, 11:49 AM UTC (e891887)">Preview</a> | <a href="https://whatpr.org/url/723/2885626...e891887.html" title="Last updated on Dec 9, 2022, 11:49 AM UTC (e891887)">Diff</a>
> Editorial: dependency cleanup

- url.bs
Also add some `<div algorithm>` wrappers to this section.
Closes #523.
---
cc @karwa
***
<a href="https://whatpr.org/url/727.html" title="Last updated on Dec 19, 2022, 3:57 PM UTC (11c6d80)">Preview</a> | <a href="https://whatpr.org/url/727/50f0b09...11c6d80.html" title="Last updated on Dec 19, 2022, 3:57 PM UTC (11c6d80)">Diff</a>
> Clarify that percent-encoding often does not roundtrip

- url.bs
Closes #501.
***
<a href="https://whatpr.org/url/726.html" title="Last updated on Dec 20, 2022, 7:59 AM UTC (3856b1f)">Preview</a> | <a href="https://whatpr.org/url/726/a05ee27...3856b1f.html" title="Last updated on Dec 20, 2022, 7:59 AM UTC (3856b1f)">Diff</a>
> Editorial: clarify the UTF-8ness of percent-encoded bytes

- url.bs
As opaque paths can end in U+0020, those trailing U+0020 code points need to be removed from the path when both query and fragment become null.
Tests: ...
Fixes #651.
* WebKit
* Gecko
* https://github.com/web-platform-tests/wpt/pull/37556
* Chromium: …
* Gecko: …
* WebKit: …
* Deno: …
* Node.js: …
***
<a href="https://whatpr.org/url/728.html" title="Last updated on Dec 16, 2022, 3:50 PM UTC (fc3bee2)">Preview</a> | <a href="https://whatpr.org/url/728/50f0b09...fc3bee2.html" title="Last updated on Dec 16, 2022, 3:50 PM UTC (fc3bee2)">Diff</a>
> Ensure the API roundtrips for opaque paths

- url.bs
As suggested in https://github.com/whatwg/url/issues/337 by David Singer.
This also formalizes single-dot and double-dot URL path segments as proper concepts and allows them to be part of the data structure rather than writing section, which is much more sound.
***
<a href="https://whatpr.org/url/736.html" title="Last updated on Jan 16, 2023, 5:59 PM UTC (739f232)">Preview</a> | <a href="https://whatpr.org/url/736/fdaa0e5...739f232.html" title="Last updated on Jan 16, 2023, 5:59 PM UTC (739f232)">Diff</a>
> Editorial: define URL path segment

- url.bs
Also slightly modernize the public suffix and registrable domain algorithm headers.
Fixes #435.
***
<a href="https://whatpr.org/url/737.html" title="Last updated on Jan 17, 2023, 8:26 AM UTC (f08996b)">Preview</a> | <a href="https://whatpr.org/url/737/2e4a19c...f08996b.html" title="Last updated on Jan 17, 2023, 8:26 AM UTC (f08996b)">Diff</a>
> Editorial: define domain label

- url.bs
This language is copied from Encoding, to which similar considerations applied.
Closes #535.
***
<a href="https://whatpr.org/url/738.html" title="Last updated on Jan 17, 2023, 8:50 AM UTC (18c1b4c)">Preview</a> | <a href="https://whatpr.org/url/738/2e4a19c...18c1b4c.html" title="Last updated on Jan 17, 2023, 8:50 AM UTC (18c1b4c)">Diff</a>
> Editorial: point out API section is not suitable for all

- url.bs
ab0e820b0b559610b30c731b7f2c1a8094181680 didn't consider the impact on the validation error infrastructure.
This also makes some minor additional changes:
* Modernizes the "Host parsing" section.
* Clarifies that the IPv4 parser cannot be invoked directly.
* Clarifies that the IPv6 parser can, but you should still not do it.
Fixes #706.
***
<a href="https://whatpr.org/url/739.html" title="Last updated on Jan 17, 2023, 12:52 PM UTC (8dfebab)">Preview</a> | <a href="https://whatpr.org/url/739/42ce81b...8dfebab.html" title="Last updated on Jan 17, 2023, 12:52 PM UTC (8dfebab)">Diff</a>
> Redo validation errors in the IPv4 parser

- url.bs
This was updated in https://github.com/w3c/FileAPI/pull/191
***
<a href="https://whatpr.org/url/751.html" title="Last updated on Feb 8, 2023, 2:37 PM UTC (0d719e9)">Preview</a> | <a href="https://whatpr.org/url/751/2f7b688...0d719e9.html" title="Last updated on Feb 8, 2023, 2:37 PM UTC (0d719e9)">Diff</a>
> Fix reference to resolve a blob URL

- README.md
This pull request adds `Ada`, a spec-compliant and fast URL parser to the implementations section of the readme. Ada is currently adopted by Node.js, and actively developed and maintained by me and Daniel Lemire (@lemire). It would be in the public interest to share a fast and compliant implementation of the URL parser.
> Add Ada to implementations section of readme

- url.bs
Editorial. This PR clarifies the return value of the IPv4 number parser.
***
<a href="https://whatpr.org/url/754.html" title="Last updated on Feb 13, 2023, 4:23 AM UTC (72e1ebf)">Preview</a> | <a href="https://whatpr.org/url/754/8653878...72e1ebf.html" title="Last updated on Feb 13, 2023, 4:23 AM UTC (72e1ebf)">Diff</a>
> Clarify return value of the IPv4 number parser

- url.bs
This addresses #406. 
By my count, there are 54 different places where a `validation error` can occur with the majority of them being unique. This adds a table with descriptive error codes for each unique validation error, which also has an associated description of the error. 
- Would there by value in adding a column indicating whether the validation error can cause the parser to fail?
- I am considering adding example input that would trigger each validation error. Is this something you think would have value?
- The `unexpected-windows-drive-letter-host` needs an error description still.
- I wasn't sure how best to link the validation errors in each spot, so I just ended up doing `<a><unique error name></a> <a>validation error</a>` everywhere. I had considered a prefix or suffix of …
> Named validation errors

- url.bs
Tests: https://github.com/web-platform-tests/wpt/pull/38655.
Fixes #163.
* Chromium
* WebKit
* https://github.com/web-platform-tests/wpt/pull/38655
* Chromium: https://bugs.chromium.org/p/chromium/issues/detail?id=1418374
* Gecko: https://bugzilla.mozilla.org/show_bug.cgi?id=1818269
* WebKit: https://bugs.webkit.org/show_bug.cgi?id=252749
* Deno: https://github.com/denoland/deno/issues/17882
* Node.js: https://github.com/nodejs/node/pull/46308
***
<a href="https://whatpr.org/url/734.html" title="Last updated on Feb 22, 2023, 4:42 PM UTC (c02d79d)">Preview</a> | <a href="https://whatpr.org/url/734/fdaa0e5...c02d79d.html" title="Last updated on Feb 22, 2023, 4:42 PM UTC (c02d79d)">Diff</a>
> Add a size getter to URLSearchParams

- url.bs
Fixes #757.
***
<a href="https://whatpr.org/url/758.html" title="Last updated on Feb 24, 2023, 10:34 AM UTC (2007e52)">Preview</a> | <a href="https://whatpr.org/url/758/12b6f0c...2007e52.html" title="Last updated on Feb 24, 2023, 10:34 AM UTC (2007e52)">Diff</a>
> host-missing validation error is fatal

- url.bs
Fixes #713.
* WebKit
* Chromium per https://matrixlogs.bakkot.com/WHATWG/2023-03-07#L2
* https://github.com/web-platform-tests/wpt/pull/39069
* Chromium: https://bugs.chromium.org/p/chromium/issues/detail?id=1425839
* Gecko: https://bugzilla.mozilla.org/show_bug.cgi?id=1823354
* WebKit: https://bugs.webkit.org/show_bug.cgi?id=254147
* Deno: https://github.com/denoland/deno/issues/18285
* Node.js: https://github.com/nodejs/node/issues/47169
***
<a href="https://whatpr.org/url/763.html" title="Last updated on Mar 20, 2023, 9:18 AM UTC (9b88b46)">Preview</a> | <a href="https://whatpr.org/url/763/6d4734a...9b88b46.html" title="Last updated on Mar 20, 2023, 9:18 AM UTC (9b88b46)">Diff</a>
> Add URL.canParse()

- url.bs
Tests: https://github.com/web-platform-tests/wpt/pull/39865.
Fixes #335.
* Chromium
* WebKit
* https://github.com/web-platform-tests/wpt/pull/39865
* Chromium: https://bugs.chromium.org/p/chromium/issues/detail?id=1442916
* Gecko: https://bugzilla.mozilla.org/show_bug.cgi?id=1831587
* WebKit: https://bugs.webkit.org/show_bug.cgi?id=256369
* Deno: https://github.com/denoland/deno/issues/19000
* Node.js: https://github.com/nodejs/node/issues/47883
***
<a href="https://whatpr.org/url/735.html" title="Last updated on May 5, 2023, 5:21 PM UTC (81412b3)">Preview</a> | <a href="https://whatpr.org/url/735/ae3c28b...81412b3.html" title="Last updated on May 5, 2023, 5:21 PM UTC (81412b3)">Diff</a>
> Add value argument to URLSearchParams's has() and delete()

- url.bs
Fixes: #770.
* …
* …
* https://github.com/web-platform-tests/wpt/pull/40133
* Chromium: …
* Gecko: [Bug 1834703](https://bugzilla.mozilla.org/show_bug.cgi?id=1834703)
* WebKit: …
* Deno: …
* Node.js: …
***
<a href="https://whatpr.org/url/771.html" title="Last updated on May 24, 2023, 12:58 PM UTC (2782e9f)">Preview</a> | <a href="https://whatpr.org/url/771/bfb9157...2782e9f.html" title="Last updated on May 24, 2023, 12:58 PM UTC (2782e9f)">Diff</a>
> Return null origin of "blob:" URL containing inner non-"http(s):" URL

- url.bs
Blocklisting blob: URLs containing a file: origin from getting a proper origin was a bridge too far. See #506 for a slightly less ambitious approach that could still work.
Closes #775.
* WebKit
* Chromium
* https://github.com/web-platform-tests/wpt/pull/41158
* Chromium: https://bugs.chromium.org/p/chromium/issues/detail?id=1448562
* Gecko: https://bugzilla.mozilla.org/show_bug.cgi?id=1834703
* WebKit: https://bugs.webkit.org/show_bug.cgi?id=257262
* Deno: https://github.com/denoland/deno/issues/19241
* Node.js: https://github.com/nodejs/node/issues/48904
***
<a href="https://whatpr.org/url/780.html" title="Last updated on Jul 24, 2023, 3:43 PM UTC (4343e39)">Preview</a> | <a …
> Keep blob: URLs containing file: origins as an exercise for the reader

- review-drafts/2023-08.bs
The [August 2023 Review Draft](https://url.spec.whatwg.org/review-drafts/2023-08/) for this Workstream will be published shortly after merging this pull request.
Under the [WHATWG IPR Policy](https://whatwg.org/ipr-policy), Participants may, within 45 days after publication of a Review Draft, exclude certain Essential Patent Claims from the Review Draft Licensing Obligations. See the [IPR Policy](https://whatwg.org/ipr-policy) for details.
***
<a href="https://whatpr.org/url/781.html" title="Last updated on Aug 21, 2023, 7:47 PM UTC (a10b01d)">Preview</a> | <a href="https://whatpr.org/url/781/fff33c3...a10b01d.html" title="Last updated on Aug 21, 2023, 7:47 PM UTC (a10b01d)">Diff</a>
> Review Draft Publication: August 2023

- url.bs
Fixes #786.
***
<a href="https://whatpr.org/url/787.html" title="Last updated on Sep 16, 2023, 3:05 PM UTC (ce9e37f)">Preview</a> | <a href="https://whatpr.org/url/787/d2ca75f...ce9e37f.html" title="Last updated on Sep 16, 2023, 3:05 PM UTC (ce9e37f)">Diff</a>
> Editorial: correct URL path serializer markup

- url.bs
Double negatives are hard to read.
***
<a href="https://whatpr.org/url/789.html" title="Last updated on Sep 20, 2023, 12:14 PM UTC (4cfb019)">Preview</a> | <a href="https://whatpr.org/url/789/b86ab66...4cfb019.html" title="Last updated on Sep 20, 2023, 12:14 PM UTC (4cfb019)">Diff</a>
> Editorial: rename host parser's isNotSpecial to isOpaque

- url.bs
Since this branch requires that `atSignSeen` is true, we must have already emitted an `invalid-credentials` validation error and this emission must be a duplicate.
What this check is actually doing is confirming that the host is not empty before it begins parsing it, so `host-missing` is a more appropriate error to emit.
* …
* …
* …
* Chromium: …
* Gecko: …
* WebKit: …
* Deno: …
* Node.js: …
***
<a href="https://whatpr.org/url/793.html" title="Last updated on Sep 26, 2023, 8:32 AM UTC (6e3c878)">Preview</a> | <a href="https://whatpr.org/url/793/45a483a...6e3c878.html" title="Last updated on Sep 26, 2023, 8:32 AM UTC (6e3c878)">Diff</a>
> Fix validation error when a URL has credentials but no host

- url.bs
I'm about to cut a new release of Bikeshed, and it'll start complaining about the unescaped `&` in these two URLs (because they look like a `&b;` character escape, but without a final semicolon and with an unknown name). This is a parse error, [per the HTML spec](https://html.spec.whatwg.org/multipage/parsing.html#named-character-reference-state).
***
<a href="https://whatpr.org/url/808.html" title="Last updated on Dec 7, 2023, 10:22 PM UTC (e7cdb7e)">Preview</a> | <a href="https://whatpr.org/url/808/aa64bb2...e7cdb7e.html" title="Last updated on Dec 7, 2023, 10:22 PM UTC (e7cdb7e)">Diff</a>
> Properly escape the &

- url.bs
This will be useful for a future version of the Cookies RFC.
Closes #792.
***
[PR Preview](https://github.com/tobie/pr-preview#pr-preview) failed to build. _(Last tried on Jan 26, 2024, 8:37 AM UTC)_.
<details>
<summary>More</summary>
PR Preview relies on a number of web services to run. There seems to be an issue with the following one:
:rotating_light: [CSS Spec Preprocessor](https://api.csswg.org/bikeshed/) - CSS Spec Preprocessor is the web service used to build Bikeshed specs.
:link: [Related URL](https://api.csswg.org/bikeshed/?url=https%3A%2F%2Fraw.githubusercontent.com%2Fwhatwg%2Furl%2Fc9b5b18196386b2e3e8d82fcd37d2f0ec95d9b2d%2Furl.bs&force=1&md-status=LS-PR&md-Text-Macro=PR-NUMBER%20812)
_If you don't have enough information above to solve the error by yourself (or to understand …
> Editorial: add a URL path concept

- review-drafts/2024-02.bs
The [February 2024 Review Draft](https://url.spec.whatwg.org/review-drafts/2024-02/) for this Workstream will be published shortly after merging this pull request.
Under the [WHATWG IPR Policy](https://whatwg.org/ipr-policy), Participants may, within 45 days after publication of a Review Draft, exclude certain Essential Patent Claims from the Review Draft Licensing Obligations. See the [IPR Policy](https://whatwg.org/ipr-policy) for details.
***
<a href="https://whatpr.org/url/823.html" title="Last updated on Feb 19, 2024, 6:44 PM UTC (1df85d9)">Preview</a> | <a href="https://whatpr.org/url/823/94b8447...1df85d9.html" title="Last updated on Feb 19, 2024, 6:44 PM UTC (1df85d9)">Diff</a>
> Review Draft Publication: February 2024

- url.bs
Tests: https://github.com/web-platform-tests/wpt/pull/45248.
Fixes #372.
* Gecko
* WebKit
* See above.
* Chromium: https://issues.chromium.org/issues/331041242
* Gecko: https://bugzilla.mozilla.org/show_bug.cgi?id=1887611
* WebKit: https://bugs.webkit.org/show_bug.cgi?id=271636
* Deno: https://github.com/denoland/deno/issues/23069
* Node.js: https://github.com/nodejs/node/issues/52208
***
<a href="https://whatpr.org/url/825.html" title="Last updated on Mar 25, 2024, 10:06 AM UTC (220b550)">Preview</a> | <a href="https://whatpr.org/url/825/ffee2e2...220b550.html" title="Last updated on Mar 25, 2024, 10:06 AM UTC (220b550)">Diff</a>
> Add URL.parse()

- review-drafts/2024-08.bs
The [August 2024 Review Draft](https://url.spec.whatwg.org/review-drafts/2024-08/) for this Workstream will be published shortly after merging this pull request.
Under the [WHATWG IPR Policy](https://whatwg.org/ipr-policy), Participants may, within 45 days after publication of a Review Draft, exclude certain Essential Patent Claims from the Review Draft Licensing Obligations. See the [IPR Policy](https://whatwg.org/ipr-policy) for details.
***
<a href="https://whatpr.org/url/832.html" title="Last updated on Aug 19, 2024, 6:23 AM UTC (ff5125a)">Preview</a> | <a href="https://whatpr.org/url/832/1c3e6ed...ff5125a.html" title="Last updated on Aug 19, 2024, 6:23 AM UTC (ff5125a)">Diff</a>
> Review Draft Publication: August 2024

- url.bs
***
<a href="https://whatpr.org/url/838.html" title="Last updated on Nov 25, 2024, 4:43 PM UTC (280ff43)">Preview</a> | <a href="https://whatpr.org/url/838/302c5af...280ff43.html" title="Last updated on Nov 25, 2024, 4:43 PM UTC (280ff43)">Diff</a>
> Editorial: adopt Infra number definitions (and redo IPv6 pieces)

- url.bs
I'm not entirely sure why this redundant check existed. Either because there was a difference back when this definition was introduced in 3bec3b89c4deb10842ba6c464c700df47c268f17 or (more likely) I wasn't sure if there was a difference.
Fixes #817.
***
<a href="https://whatpr.org/url/840.html" title="Last updated on Nov 29, 2024, 8:21 AM UTC (d0f8256)">Preview</a> | <a href="https://whatpr.org/url/840/7ff8de0...d0f8256.html" title="Last updated on Nov 29, 2024, 8:21 AM UTC (d0f8256)">Diff</a>
> Remove redundant domain to Unicode call from valid domain

- url.bs
It makes more sense if it's consistent with UseSTD3ASCIIRules and VerifyDnsLength.
Fixes #820.
***
<a href="https://whatpr.org/url/842.html" title="Last updated on Nov 29, 2024, 9:13 AM UTC (96bafa6)">Preview</a> | <a href="https://whatpr.org/url/842/7ff8de0...96bafa6.html" title="Last updated on Nov 29, 2024, 9:13 AM UTC (96bafa6)">Diff</a>
> Set IDNA's CheckHyphens to the value of beStrict

- url.bs
Also move UseSTD3ASCIIRules around in Unicode ToASCII to align with the UTS46 order.
While this is not a change in behavior, this is not marked as editorial as UTS46 integration is somewhat significant and worth highlighting.
Fixes #821.
***
<a href="https://whatpr.org/url/843.html" title="Last updated on Nov 29, 2024, 10:03 AM UTC (b488759)">Preview</a> | <a href="https://whatpr.org/url/843/cd8f1d6...b488759.html" title="Last updated on Nov 29, 2024, 10:03 AM UTC (b488759)">Diff</a>
> Set IDNA's IgnoreInvalidPunycode to false

- url.bs
Fixes #818.
***
<a href="https://whatpr.org/url/841.html" title="Last updated on Nov 29, 2024, 8:43 AM UTC (d04a7dd)">Preview</a> | <a href="https://whatpr.org/url/841/7ff8de0...d04a7dd.html" title="Last updated on Nov 29, 2024, 8:43 AM UTC (d04a7dd)">Diff</a>
> Editorial: check forbidden domain code points in domain to ASCII

- url.bs
VerifyDnsLength will take care of it otherwise. (See #497 for additional context.)
***
<a href="https://whatpr.org/url/845.html" title="Last updated on Dec 2, 2024, 4:08 PM UTC (d4110e0)">Preview</a> | <a href="https://whatpr.org/url/845/c3d173f...d4110e0.html" title="Last updated on Dec 2, 2024, 4:08 PM UTC (d4110e0)">Diff</a>
> Editorial: only care about the empty string when beStrict is false

- review-drafts/2025-02.bs
The [February 2025 Review Draft](https://url.spec.whatwg.org/review-drafts/2025-02/) for this Workstream will be published shortly after merging this pull request.
Under the [WHATWG IPR Policy](https://whatwg.org/ipr-policy), Participants may, within 45 days after publication of a Review Draft, exclude certain Essential Patent Claims from the Review Draft Licensing Obligations. See the [IPR Policy](https://whatwg.org/ipr-policy) for details.
***
<a href="https://whatpr.org/url/857.html" title="Last updated on Feb 18, 2025, 6:13 PM UTC (d91b4be)">Preview</a> | <a href="https://whatpr.org/url/857/cce98e5...d91b4be.html" title="Last updated on Feb 18, 2025, 6:13 PM UTC (d91b4be)">Diff</a>
> Review Draft Publication: February 2025

- url.bs
Closes #607. 
---
* Chromium
* Gecko
* WebKit (@achristensen07 FYI)
* https://github.com/web-platform-tests/wpt/pull/51093
* Chromium: N/A
* Gecko: https://bugzilla.mozilla.org/show_bug.cgi?id=1951702
* WebKit: https://bugs.webkit.org/show_bug.cgi?id=289083
* Deno: https://github.com/denoland/deno/issues/28386
* Node.js: https://github.com/nodejs/node/issues/57313
***
<a href="https://whatpr.org/url/846.html" title="Last updated on Mar 4, 2025, 4:30 PM UTC (056d2f6)">Preview</a> | <a href="https://whatpr.org/url/846/7f3e3b6...056d2f6.html" title="Last updated on Mar 4, 2025, 4:30 PM UTC (056d2f6)">Diff</a>
> Add U+005E (^) to the path percent-encode set

- url.bs
In fdaa0e5a3790693a82f578d7373f216d8fef9ac8 we tackled a problem whereby removing the fragment or query from a URL with an opaque path through the API would not make the URL roundtrip due to the opaque path being able to end in non-percent-encoded spaces.
However, this failed to address other ways of serializing the URL. As such this is a new approach whereby opaque paths simply cannot end with non-percent-encoded spaces. Enforcing this in the URL parser allows us to completely revert the aforementioned commit, greatly simplifying the API implementation.
Fixes #784.
---
* Chromium (at least during Interop 2024)
* Gecko
* WebKit
* https://github.com/web-platform-tests/wpt/pull/51129
* Chromium: https://issues.chromium.org/issues/400919461
* Gecko: …
> Ensure opaque paths always roundtrip

- url.bs
URLPattern's canonicalize a hostname is the only invocation of the basic URL parser with a URL and state override set to hostname state that looks at the return failure.
And since the URL that URLPattern uses is a dummy URL that is ideally not exposed, knowing about all the failure conditions is kind of important.
(Now technically the second return failure added here cannot be observed as the dummy URL won't have credentials or a non-null port, but it seemed good to change that at the same time for consistency.)
This is covered by existing URLPattern web-platform-tests. Some more background can be found in https://github.com/whatwg/urlpattern/issues/252.
* Required by URLPattern.
* URLPattern tests.
* Chromium: N/A, to be filed as part of URLPattern changes.
* Gecko: N/A, to be filed as …
> Report all hostname state failures for URLPattern

- url.bs
I noticed this algorithm in the infra spec, and I believe this is what all engines already do for the sort.
Hopefully not mistaken!
***
<a href="https://whatpr.org/url/872.html" title="Last updated on May 12, 2025, 7:54 AM UTC (216797e)">Preview</a> | <a href="https://whatpr.org/url/872/cc8b776...216797e.html" title="Last updated on May 12, 2025, 7:54 AM UTC (216797e)">Diff</a>
> Editorial: Use code unit less than algorithm for URLSearchParams sort
