whatwg/url

url.bs, url.html
At least, I'm assuming that's what the intention was for this XXX'd sentence.
=> Schemes should be registered with IANA

url.bs, url.html
=> Have new URLSearchParams() remove a leading "?"

url.bs, url.html
Ref. https://github.com/whatwg/html/issues/654#issuecomment-243696548
=> Editorial: Update spelling of HTML terms to en-US

url.bs, url.html
=> Clarify the informative nature of referenced RFCs

url.bs, url.html
=> Editorial: add a note and example for query encoding

url.bs, url.html
=> Meta: export "is local"

url.bs, url.html
=> URL's href attribute needs to reset URLSearchParams too

url.bs
=> Percent encode fragments too

url.bs
=> Editorial: clarify that a trailing dot is significant

url.bs
Fixes: https://github.com/whatwg/url/issues/173
=> Editorial: removing extra "and" in IPv4 parser

url.bs
=> Editorial: reduce ambiguity in syntax section

url.bs
=> Editorial: use simple/y less

url.bs
Ref: #201
***
[Preview](https://s3.amazonaws.com/pr-preview/TimothyGu/url/patch-1.html) | [Diff](https://s3.amazonaws.com/pr-preview/whatwg/url/1d69a77..TimothyGu:patch-1:091d348.html)
=> Editorial: remove one more instance of "simply"

url.bs
Fixes #47.
***
[Preview](https://url.spec.whatwg.org/branch-snapshots/annevk/infra-take-n/) | [Diff](https://s3.amazonaws.com/pr-preview/whatwg/url/9f1c19d...c583aac.html)
=> Editorial: format bytes and code points per Infra

README.md
Addresses:
- https://github.com/whatwg/meta/issues/65
=> Editorial: Link to whatwg/meta documents

url.bs
***
<a href="https://whatpr.org/url/422.html" title="Last updated on Dec 12, 2018, 11:44 AM GMT (cf5ca9a)">Preview</a> | <a href="https://whatpr.org/url/422/85d96e2...cf5ca9a.html" title="Last updated on Dec 12, 2018, 11:44 AM GMT (cf5ca9a)">Diff</a>
=> Editorial: Bugzilla is no longer used, update reference

url.bs
Fixes #439.
***
<a href="https://whatpr.org/url/485.html" title="Last updated on Apr 26, 2020, 3:00 PM UTC (3ec3322)">Preview</a> | <a href="https://whatpr.org/url/485/980ba89...3ec3322.html" title="Last updated on Apr 26, 2020, 3:00 PM UTC (3ec3322)">Diff</a>
=> Editorial: assert that init is a string

url.bs
Fixes #358.
@mithrandi  what do you think?
***
<a href="https://whatpr.org/url/483.html" title="Last updated on Apr 26, 2020, 2:24 PM UTC (b4b95d5)">Preview</a> | <a href="https://whatpr.org/url/483/980ba89...b4b95d5.html" title="Last updated on Apr 26, 2020, 2:24 PM UTC (b4b95d5)">Diff</a>
=> Remove "holding data" and add // example

url.bs
Closes #373 and closes #480.
@rmisev @domenic @alercah @mattto would appreciate your feedback on this clarification.
***
<a href="https://whatpr.org/url/488.html" title="Last updated on May 4, 2020, 1:35 PM UTC (c75037d)">Preview</a> | <a href="https://whatpr.org/url/488/d8fb1a4...c75037d.html" title="Last updated on May 4, 2020, 1:35 PM UTC (c75037d)">Diff</a>
=> Editorial: improve the URL parser

url.bs
***
<a href="https://whatpr.org/url/492.html" title="Last updated on May 5, 2020, 1:15 PM UTC (56e851b)">Preview</a> | <a href="https://whatpr.org/url/492/909218b...56e851b.html" title="Last updated on May 5, 2020, 1:15 PM UTC (56e851b)">Diff</a>
=> Clarify that a domain is never empty

url.bs
Helps with #282.
***
<a href="https://whatpr.org/url/493.html" title="Last updated on May 5, 2020, 3:29 PM UTC (c806d34)">Preview</a> | <a href="https://whatpr.org/url/493/909218b...c806d34.html" title="Last updated on May 5, 2020, 3:29 PM UTC (c806d34)">Diff</a>
=> IPv4 parser cleanup

url.bs
Closes #273. Follow-up #510.
***
<a href="https://whatpr.org/url/511.html" title="Last updated on May 11, 2020, 5:56 AM UTC (1a19460)">Preview</a> | <a href="https://whatpr.org/url/511/68aad5d...1a19460.html" title="Last updated on May 11, 2020, 5:56 AM UTC (1a19460)">Diff</a>
=> Editorial: avoid using non-special scheme

url.bs
***
<a href="https://whatpr.org/url/547.html" title="Last updated on Sep 29, 2020, 3:05 PM UTC (b3647b2)">Preview</a> | <a href="https://whatpr.org/url/547/c9ff1d9...b3647b2.html" title="Last updated on Sep 29, 2020, 3:05 PM UTC (b3647b2)">Diff</a>
=> Meta: link Review Draft

url.bs
The reign of flags is over, except for IDs. Complements #575.
***
<a href="https://whatpr.org/url/576.html" title="Last updated on Feb 1, 2021, 8:31 AM UTC (29ffc3e)">Preview</a> | <a href="https://whatpr.org/url/576/cce3e18...29ffc3e.html" title="Last updated on Feb 1, 2021, 8:31 AM UTC (29ffc3e)">Diff</a>
=> Editorial: go all in on booleans

url.bs
This would be useful for Fetch to define a couple more aspects of connections.
Context: https://github.com/whatwg/fetch/issues/1243.
***
<a href="https://whatpr.org/url/610.html" title="Last updated on Jun 1, 2021, 12:30 PM UTC (217e57f)">Preview</a> | <a href="https://whatpr.org/url/610/1b8b8c5...217e57f.html" title="Last updated on Jun 1, 2021, 12:30 PM UTC (217e57f)">Diff</a>
=> Editorial: define and export IP address

url.bs
Ref: https://github.com/tc39/proposal-shadowrealm/issues/331
* Positive initial signals from Google, Apple, Mozilla on the general direction.
* …
* Chrome: https://bugs.chromium.org/p/chromium/issues/detail?id=1281880
* Firefox: https://bugzilla.mozilla.org/show_bug.cgi?id=1747059
* Safari: https://bugs.webkit.org/show_bug.cgi?id=234554
***
<a href="https://whatpr.org/url/657.html" title="Last updated on Oct 12, 2021, 2:57 PM UTC (a53119e)">Preview</a> | <a href="https://whatpr.org/url/657/4edcc9f...a53119e.html" title="Last updated on Oct 12, 2021, 2:57 PM UTC (a53119e)">Diff</a>
***
<a href="https://whatpr.org/url/657.html" title="Last updated on Dec 21, 2021, 1:47 PM UTC …
=> Expose URL/URLSearchParams everywhere

url.bs
Also move the anchors and link-defaults blocks around.
***
<a href="https://whatpr.org/url/714.html" title="Last updated on Oct 26, 2022, 1:02 PM UTC (59fcdb0)">Preview</a> | <a href="https://whatpr.org/url/714/6827fbe...59fcdb0.html" title="Last updated on Oct 26, 2022, 1:02 PM UTC (59fcdb0)">Diff</a>
=> Meta: my employer changed

url.bs
This could be taken even further, but this seems like a good first step.
***
<a href="https://whatpr.org/url/717.html" title="Last updated on Dec 5, 2022, 9:09 AM UTC (c9c4c72)">Preview</a> | <a href="https://whatpr.org/url/717/48f1e79...c9c4c72.html" title="Last updated on Dec 5, 2022, 9:09 AM UTC (c9c4c72)">Diff</a>
=> Editorial: adopt Infra for URLSearchParams

url.bs
Closes #740.
***
<a href="https://whatpr.org/url/741.html" title="Last updated on Jan 19, 2023, 10:02 AM UTC (f772e84)">Preview</a> | <a href="https://whatpr.org/url/741/3c4befa...f772e84.html" title="Last updated on Jan 19, 2023, 10:02 AM UTC (f772e84)">Diff</a>
=> Meta: preserve IDs per anchor permanence policy

url.bs
***
<a href="https://whatpr.org/url/745.html" title="Last updated on Jan 23, 2023, 1:05 PM UTC (c7061f7)">Preview</a> | <a href="https://whatpr.org/url/745/f0806d6...c7061f7.html" title="Last updated on Jan 23, 2023, 1:05 PM UTC (c7061f7)">Diff</a>
=> Editorial: rely on Infra's code point length

url.bs
Fixes #790.
***
<a href="https://whatpr.org/url/791.html" title="Last updated on Sep 25, 2023, 6:46 AM UTC (e6ad01f)">Preview</a> | <a href="https://whatpr.org/url/791/9057992...e6ad01f.html" title="Last updated on Sep 25, 2023, 6:46 AM UTC (e6ad01f)">Diff</a>
=> Editorial: remove duplicate "is"

README.md
Add the additional formatting rules that originated in Fetch.
=> Meta: update repository files

url.bs
***
<a href="https://whatpr.org/url/826.html" title="Last updated on Mar 25, 2024, 10:37 AM UTC (faf1b63)">Preview</a> | <a href="https://whatpr.org/url/826/58acb06...faf1b63.html" title="Last updated on Mar 25, 2024, 10:37 AM UTC (faf1b63)">Diff</a>
=> Editorial: adopt <div algorithm> throughout

.github/workflows/build.yml, PULL_REQUEST_TEMPLATE.md, url.bs
Closes #834.
***
<a href="https://whatpr.org/url/835.html" title="Last updated on Sep 20, 2024, 3:06 PM UTC (375b443)">Preview</a> | <a href="https://whatpr.org/url/835/5861e02...375b443.html" title="Last updated on Sep 20, 2024, 3:06 PM UTC (375b443)">Diff</a>
=> Meta: link Simplified Chinese translation

url.bs
***
<a href="https://whatpr.org/url/858.html" title="Last updated on Feb 18, 2025, 6:05 PM UTC (910b9b6)">Preview</a> | <a href="https://whatpr.org/url/858/7f3e3b6...910b9b6.html" title="Last updated on Feb 18, 2025, 6:05 PM UTC (910b9b6)">Diff</a>
=> Meta: address Bikeshed errors

url.bs
In particular for inputs that do not start with an ASCII digit.
Tests: https://github.com/web-platform-tests/wpt/pull/51505.
This fixes https://github.com/whatwg/urlpattern/issues/266.
* WebKit
* Chromium
* See above.
* Chromium: https://issues.chromium.org/issues/405793112
* Gecko: N/A, no URLPattern implementation
* WebKit: N/A
* Deno: N/A?
* Node.js: N/A?
***
<a href="https://whatpr.org/url/866.html" title="Last updated on Mar 24, 2025, 8:53 AM UTC (cdd32a1)">Preview</a> | <a href="https://whatpr.org/url/866/c23aec1...cdd32a1.html" title="Last updated on Mar 24, 2025, 8:53 AM UTC (cdd32a1)">Diff</a>
=> Make port state override return failure more for URLPattern
